name: CI
on: [push, pull_request]
jobs:
  cs-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup
        uses: shivammathur/setup-php@2.0.0
        with:
          php-version: 7.2
          extensions: mbstring, fileinfo, json, intl, dom
      - name: install
        run: composer update --prefer-stable
      - name: 'php-cs-fixer check'
        run: 'vendor/bin/php-cs-fixer fix --dry-run --diff'
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      matrix:
        php-versions:  ['7.2', '7.3', '7.4']
    name: tests-${{ matrix.php-versions }}
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup
        uses: shivammathur/setup-php@2.0.0
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, fileinfo, json, intl, dom
      - name: install
        run: composer update --prefer-stable
      - name: tests
        run: vendor/bin/phpunit
  tests-lowest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup
        uses: shivammathur/setup-php@2.0.0
        with:
          php-version: 7.2
          extensions: mbstring, fileinfo, json, intl, dom
      - name: install
        run: composer update --prefer-lowest --prefer-stable
      - name: tests
        run: vendor/bin/phpunit
